import 'package:KiDo/bloc/page_bloc.dart';
import 'package:KiDo/services/services.dart';
import 'package:KiDo/shared/shared.dart';
import 'package:KiDo/ui/sections/sections.dart';
import 'package:KiDo/ui/widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:KiDo/models/models.dart' as Model;

part 'menu-page.dart';
part 'splash-page.dart';
part 'judul-doa.dart';
part 'content-doa.dart';
part 'favorite-page.dart';
part 'favorite-detail-page.dart';
part 'search-page.dart';
part 'information.dart';
part 'persiapan-page.dart';
part 'cached-page.dart';
